"""initial migration

Revision ID: 7d55d3cf93c0
Revises: 
Create Date: 2022-10-31 10:38:42.088999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d55d3cf93c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('moduleNum', sa.String(length=4), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('wightage', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('isDone', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_title'), 'assessment', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_title'), table_name='assessment')
    op.drop_table('assessment')
    # ### end Alembic commands ###
