"""empty message

Revision ID: b031e862e2ce
Revises: 7d55d3cf93c0
Create Date: 2022-10-31 13:21:55.416143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b031e862e2ce'
down_revision = '7d55d3cf93c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment', 'wightage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment', sa.Column('wightage', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
